export const bankNames = [
    "ABANCA Portugal",
    "ActivoBank",
    "Banco BAI Europa",
    "Banco Best",
    "Banco Bilbao Vizcaya Argentaria Portugal",
    "Banco BNP Paribas Personal Finance",
    "Banco BPI",
    "Banco Carregosa",
    "Banco Credibom",
    "Banco CTT",
    "Banco de Investimento Global",
    "Banco Efisa",
    "Banco Finantia",
    "Banco Invest",
    "Banco Santander Totta",
    "Caixa Geral de Depósitos (CGD)",
    "Cofidis Portugal",
    "EuroBic",
    "Millennium BCP",
    "Novo Banco",
];