export const bankNames = [
    "Caixa Geral de Depósitos (CGD)",
    "Millennium BCP",
    "Banco Santander Totta",
    "Novo Banco",
    "Banco BPI",
    "ActivoBank",
    "Banco CTT",
    "ABANCA Portugal",
    "EuroBic",
    "Banco Best",
    "Banco Invest",
    "Banco Finantia",
    "Banco Carregosa",
    "Banco BAI Europa",
    "Banco de Investimento Global",
    "Banco Credibom",
    "Cofidis Portugal",
    "Banco BNP Paribas Personal Finance",
    "Banco Efisa",
    "Banco Bilbao Vizcaya Argentaria Portugal",
]