export const bankNames = [
    "ABANCA Portugal",
    "ActivoBank",
    "BAI Europa",
    "Best",
    "Bilbao Vizcaya Argentaria Portugal",
    "BNP Paribas Personal Finance",
    "BPI",
    "Carregosa",
    "Credibom",
    "CTT",
    "de Investimento Global",
    "Efisa",
    "Finantia",
    "Invest",
    "Santander Totta",
    "Caixa Geral de Depósitos (CGD)",
    "Cofidis Portugal",
    "EuroBic",
    "Millennium BCP",
    "Novo Banco",
];