export const USER_STATUS = {
  PENDING: "PENDING",
  SUBMITTED: "SUBMITTED",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
} as const;

export const USER_ROLE = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  CUSTOMER: "CUSTOMER",
  FLEET_MANAGER: "FLEET_MANAGER",
  VENDOR: "VENDOR",
  SUB_VENDOR: "SUB_VENDOR",
  DELIVERY_PARTNER: "DELIVERY_PARTNER",
} as const;
